package: postgresql
user: lmatthieu

platform:
  # - linux-32
  - linux-64
  # - win-32
  # - win-64
  # - osx-64

engine:
  - python=2

script:
  - yum install -y libreadline-dev
  - conda build  .

build_targets: conda
